### ISSUE TITLE
Upgrade Faraday to v 1.0

### ISSUE THREAD

**Issue by AxelTheGerman** [plivo/plivo-ruby#124]
Faraday is used in this gem and locked to `0.x` - other gems use Faraday as well and start requiring `1.x`

Doesn't seem like there are many breaking changes in this release, see https://github.com/lostisland/faraday/blob/master/CHANGELOG.md#v10
However, I don't know much about Faraday so not sure what is required to upgrade plivo - or if it maybe could work with `0.x` and `1.x` of faraday.

Going forward this will cause more and more conflicts with other gems, i.e. preventing Plivo users from upgrading those other gems. This will get even worse if an update is required for a new feature or security fixes in those gems.

Thanks!

**Comment by AxelTheGerman** [comment]
@nixonsam the plivo gem is still the only one on my Gemfile preventing me from upgrading to faraday 1.x - any update on this? Is this too much effort or needs more information?

**Comment by kunal-plivo** [comment]
@AxelTheGerman please subscribe to updates on https://github.com/plivo/plivo-ruby/pull/136

**Comment by huzaif-plivo** [comment]
@AxelTheGerman The SDK is updated with the required recommendations since the release of [v4.10.0](https://github.com/plivo/plivo-ruby/releases/tag/v4.10.0). However, we recommend you try our latest version [v4.15.0](https://github.com/plivo/plivo-ruby/releases/tag/v4.15.0). Feel free to contact our [support team](support.plivo.com/hc/en-us) for any further issues.
