### ISSUE TITLE
Tags are out of sync with rubygems.org releases

### ISSUE THREAD

**Issue by Jason733i** [plivo/plivo-ruby#170]
It seems like the tags following 4.18.0 have not been pushed. I'd like to be able to compare code changes to this library so that I can more easily identify the changes that I'll have to make in my own application when updating the plivo gem.

**Comment by huzaif-plivo** [comment]
@Jason733i Thank you for bringing this to our attention! I discovered that the tags were incorrectly updated, which means that after version 4.18.0, the tags were updated without the v at the beginning, and thus we don't see them in order. You can find them at the bottom, as shown below, and we have shared this information internally so that the tags will be updated appropriately going forward. If you require any additional assistance, please feel free to contact our [support team](https://support.plivo.com/hc/en-us).

![github-ruby](https://user-images.githubusercontent.com/43034298/156578294-2362cb27-f678-45ef-807f-78233f8b5f98.png)
