### ISSUE TITLE
More robust handling of unexpected responses

### ISSUE THREAD

**Issue by brianatwhistle** [plivo/plivo-ruby#52]
On occasion, when the Plivo backend returns a response that doesn't quite conform to the expected successful response, it will raise errors in our code originating from the Plivo gem.  One specific example of this happened on February 10 in which we got a bunch of these errors:

`JSON::ParserError: A JSON text must at least contain two octets!` originating from line 63 of `plivo.rb`.  

An improvement would be to wrap it in some kind of Plivo-namespaced error so that our code can specifically look for this class of errors.  For now we have to catch that specific type of error in our code, which feels hacky.

**Comment by andey** [comment]
I'm also getting `NoMethodError: undefined method `http_code' for #<Encoding::UndefinedConversionError:0x007f7cf0f93b60>` from the plivo gem. 

I co-sign that the plivo could use better error handling.

**Comment by plivo-sdks** [comment]
@brianatwhistle @andey Apologies for not responding back earlier. The API isn't supposed to send an empty response (except for a 204 DELETE). The 4.0 version of the SDK provides for better error handling, and I think this issue is covered there. Closing this for now as we won't be adding this to the old versions of SDK.

If you have an API request ID related this empty response, please send it over so we can investigate what might be causing the issue.
