### ISSUE TITLE
NameError: uninitialized constant Plivo::Utils::Base64 while validating v2 signature

### ISSUE THREAD

**Issue by Sreyanth** [plivo/plivo-ruby#55]
Seems like Base64 has some namespacing issues and instead of taking`Base64` from `require 'base64'`, it is being searched in `Plivo::Utils`. Including the require statement while running the validation is working fine.

Need to check the tests too - all of them are passing, so there is something more to this.

Ruby version: 2.4.0p0
SDK version: 4.0.0.beta.2

**Comment by Abhishek-plivo** [comment]
Base64 should not have worked in `Plivo::Utils` as `require 'base64'` was missing there. But it was working sometimes because whenever Plivo rest client was initialized before signature validation, it would load the `base64` before signature validation and hence `Base64.encode64` would be working just fine. 

adding `require 'base64'` in lib/plivo/utils.rb will fix the issue.
pull request https://github.com/plivo/plivo-ruby/pull/56 contains the fix
